server:
  port: 8001

#加载Mybatis的配置文件和映射文件
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  #给实体类去个别名
  type-aliases-package: com.os.springcloud.entities
  #加载MyBatis的映射文件
  mapper-locations: mybatis/mapper/**/*.xml

#当前微服务取个别名
spring:
  application:
    name: wudongyuApp
    #配置连接数据库的信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: root


#客户端注册进eureka服务列表内
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      #defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: wodongyuApp8001-hystrix #给当前服务取别名
    prefer-ip-address: true #将微服务别名对应到具体的IP地址

info:
  app.name: wdy-microservicecloud
  company.name: www.wdy.com
  build.artifactId: microservicecloud_provider_dept_8001
  build.version: 1.0-SNAPSHOT